### See helm stable chart to apply other settings of MYSQL.
### Link : https://github.com/helm/charts/tree/master/stable/mysql
mysql:
  enable: true
  # docker image
  image: "pinpointdocker/pinpoint-mysql"
  # tag
  imageTag: "2.1.0"

  ## Specify password for root user
  ## Default: random 10 character string
  mysqlRootPassword: root123

  ## Create a database user
  mysqlUser: admin

  ## Default: random 10 character string
  mysqlPassword: admin

  ## Create a database
  mysqlDatabase: pinpoint

  ## Extra Initial Script
  # initializationFiles:     
  #   extra_init.sql: |-
  #     CREATE TABLE ...

### See helm stable chart to apply other settings of Zookeeper.
### Link : https://github.com/helm/charts/tree/master/incubator/zookeeper
zookeeper: 
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size : 10Gi

### See helm stable chart to apply other settings of HDFS.
### Link : https://github.com/Gradiant/charts/tree/master/charts/hdfs
hdfs:
  enabled: true
  nameNode:
    pdbMinAvailable: 1
    port: 8020
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "400m"

  dataNode:
    replicas: 3  # ensure this value is higher or equal to 'conf.hdfsSite.dfs.replication'
    pdbMinAvailable: 3  # ensure to set this value before deploying
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "400m"
  persistence:
    dataNode:
      enabled: true
      size: "20Gi"

    nameNode:
      enabled: true
      size : "20Gi"
      
pinpoint-web:
  ### If you want to use external MySQL or other settings that are different from default values, fill these fields.
  ### When the field is empty, it applies the default value.
  ### Default Value
  ###   mysql.host : pinpoint-mysql
  ###   mysql.port : 3306
  ###   mysql.user : admin
  ###   mysql.password : admin
  mysql:
    host: 
    port: 
    user: 
    password: 
    database: 
  
  ### External zookeeper address (Default : pinpoint-zookeeper) 
  zookeeper: 
    host:

pinpoint-collector:
  ### External zookeeper address (Default : pinpoint-zookeeper) 
  zookeeper:
    host: